spring :
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/prac?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: heesung
    password : heesung
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html

  jpa :
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

logging.level:
  org.hibernate.SQL: debug
  org.apche.coyote.http11: debug